### ISSUE TITLE
Data migrated, can't run the manual migrations anymore

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#41]
I pulled the v2.1.0 code and rebuilt the app within Docker (using **docker-compose build**). When starting the app, the prisma db migrations happened as expected, but what's the best way to run the remaining migrations when deploying via Docker?

```
builder_1  | The following migrations have been applied:
builder_1  |
builder_1  | migrations/
builder_1  |   └─ 20220513223344_add_workspaces/
builder_1  |     └─ migration.sql
builder_1  |   └─ 20220514235014_remove_owner_id/
builder_1  |     └─ migration.sql
builder_1  |
builder_1  | All migrations have been successfully applied.
builder_1  | info  - Loaded env from /app/.env.production
builder_1  | Listening on port 3000
```

_Originally posted by @teq-dev in https://github.com/baptisteArno/typebot.io/issues/37#issuecomment-1128338850_

**Comment by teq-dev** [comment]
Thank you. Luckily, I had a snapshot of my VM, so I was able to recover back to v2.0.  So, now should be able to pull v2.1.0 and run **docker-compose build**?

**Comment by baptisteArno** [comment]
There is an issue in the timeline, it will fail because of #37. I need to rewrite history. I'll let you know when it's done

**Comment by baptisteArno** [comment]
You should be good to go. Sorry for the mess. 😁

Let me know

**Comment by teq-dev** [comment]
Recent attempt. Merged latest code. Ran docker-compose build. Here's the output:
```
builder_1  | Waiting 5s for db to be ready...
viewer_1   | info  - Loaded env from /app/.env.production
viewer_1   | Listening on port 3000
builder_1  | Prisma schema loaded from prisma/schema.prisma
builder_1  | Datasource "db": PostgreSQL database "typebot", schema "public" at "db:5432"
db_1       | 2022-05-17 21:49:27.117 UTC [34] LOG:  could not receive data from client: Connection reset by peer
builder_1  |
builder_1  | 17 migrations found in prisma/migrations
builder_1  |
builder_1  | Applying migration `20220513223344_add_workspaces`
builder_1  | Applying migration `20220514235014_remove_owner_id`
builder_1  |
builder_1  | The following migrations have been applied:
builder_1  |
builder_1  | migrations/
builder_1  |   └─ 20220513223344_add_workspaces/
builder_1  |     └─ migration.sql
builder_1  |   └─ 20220514235014_remove_owner_id/
builder_1  |     └─ migration.sql
builder_1  |
builder_1  | All migrations have been successfully applied.
builder_1  | info  - Loaded env from /app/.env.production
builder_1  | Listening on port 3000```

Here's what I'm seeing after logging in:
![image](https://user-images.githubusercontent.com/90119409/168916428-71280757-9638-491a-9e1e-7eefa24102aa.png)

**Comment by baptisteArno** [comment]
Did you first pull v2.1.0, then ran the migration (`yarn start:workspaces:migration`), and then pull master?

**Comment by teq-dev** [comment]
I merged all upstream changes from your v.2.1.0 then ran docker-compose build. I thought this would handle the migration steps. I think I may just start over with a fresh installation of v.2.1.0 and import my typebots. All good!

**Comment by baptisteArno** [comment]
When we say v2.1.0, we are both talking about the commit with the tag `v2.1.0`, right?

Because on this commit, you shouldn't have the `20220514235014_remove_owner_id` migration.

**Comment by teq-dev** [comment]
Ah! That was the step I was ignoring. _When I actually followed your latest instructions step by step_, it worked! 

**A few notes for the v2.1.0 migration using the Docker self-hosting option:**

1. Only pull the commits up to the v2.1.0 branch:

     This is what I did:

     `git fetch origin v2.1.0`
     `git merge 210bad32f905e0556cc56757d3327ed6c91b8851`

2. By default, the Postgres container does not publish a port on the host machine. Since I ran the `yarn start:workspaces:migration` command on the host itself, I had to update docker-compose.yml to temporarily publish port 5432 for Postgres to allow the DB connection for the migration process.

**Question**: Up until now, the migrations have been happening automatically during the Docker build process. Is there a way to make the v2.1.0 migrations happen that way as well?

**Comment by baptisteArno** [comment]
Thank you for all the information. That helps a lot. I updated the instructions.

Yes indeed, the Database URL needs to be accessible outside of the docker_compose network.

> Question: Up until now, the migrations have been happening automatically during the Docker build process. Is there a way to make the v2.1.0 migrations happen that way as well?

Prisma still doesn't allow to do "complex" migrations (See https://github.com/prisma/prisma/issues/4688). So it needs to be an external script.
Because the migration isn't smooth enough, I won't do something like this for future upgrades. You won't have to do such manipulation again.
